version: "3.8"
services:
  db-okapi:
    container_name: postgresql-okapi
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=okapi
      - POSTGRES_PASSWORD=okapi25
      - POSTGRES_DB=okapi
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5